<a href="https://colab.research.google.com/github/Sanskriti10247/GoogleColabworks/blob/main/Data_Analytics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a=np.array([1,2,3,4])

a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
condition= a % 2==1
condition

array([ True, False,  True, False])

In [ ]:
#masking
a[condition]

array([1, 3])

In [ ]:
import pandas as pd


In [ ]:
movies=pd.read_csv('/content/movies.csv')
movies.head()

MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3898 entries, 0 to 3897
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MovieID  3898 non-null   int64 
 1   Title    3895 non-null   object
 2   Genres   3868 non-null   object
dtypes: int64(1), object(2)
memory usage: 91.5+ KB


In [ ]:
movies.describe()

MovieID
count  3898.000000
mean   1978.449461
std    1151.084096
min       1.000000
25%     971.250000
50%    2002.500000
75%    2976.750000
max    3952.000000

from matplotlib import pyplot as plt
_df_2['MovieID'].plot(kind='hist', bins=20, title='MovieID')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['MovieID'].plot(kind='line', figsize=(8, 4), title='MovieID')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
type(movies)

pandas.core.frame.DataFrame

In [ ]:
movies['Title'].isna()

0       False
1       False
2       False
3       False
4       False
        ...  
3893    False
3894    False
3895     True
3896    False
3897    False
Name: Title, Length: 3898, dtype: bool

In [ ]:
movies[movies['Title'].isna()]

MovieID Title           Genres
3884        7   NaN  Action|Thriller
3889       11   NaN              NaN
3895       16   NaN           Comedy

In [ ]:
movies[movies.MovieID==5 ]

MovieID                               Title  Genres
4        5  Father of the Bride Part II (1995)  Comedy

In [ ]:
movies1= movies[~movies['Title'].isna()]

In [ ]:
movies1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3895 entries, 0 to 3897
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MovieID  3895 non-null   int64 
 1   Title    3895 non-null   object
 2   Genres   3866 non-null   object
dtypes: int64(1), object(2)
memory usage: 121.7+ KB


In [ ]:
movies1['Genres']=movies1['Genres'].fillna('missing genre')
movies1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3895 entries, 0 to 3897
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MovieID  3895 non-null   int64 
 1   Title    3895 non-null   object
 2   Genres   3895 non-null   object
dtypes: int64(1), object(2)
memory usage: 121.7+ KB


<ipython-input-47-beb6f3765019>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1['Genres']=movies1['Genres'].fillna('missing genre')


In [ ]:
movies1['Genres'].fillna('missing genre',inplace=True)
movies1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3895 entries, 0 to 3897
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MovieID  3895 non-null   int64 
 1   Title    3895 non-null   object
 2   Genres   3895 non-null   object
dtypes: int64(1), object(2)
memory usage: 121.7+ KB


<ipython-input-48-402034c67f7b>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies1['Genres'].fillna('missing genre',inplace=True)
<ipython-input-48-402034c67f7b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1['Genres'].fillna('missing genre',inplace=True)


In [ ]:
movies1[['Title','MovieID']]

Title  MovieID
0                       Toy Story (1995)        1
1                         Jumanji (1995)        2
2                Grumpier Old Men (1995)        3
3               Waiting to Exhale (1995)        4
4     Father of the Bride Part II (1995)        5
...                                  ...      ...
3892  Dracula: Dead and Loving It (1995)       14
3893                      Jumanji (1995)        7
3894                        Balto (1995)       15
3896                        Nixon (1995)       17
3897             Cutthroat Island (1995)       18

[3895 rows x 2 columns]

In [ ]:
type(movies1[['Title']])

pandas.core.frame.DataFrame

In [ ]:
movies1['Title'].nunique()

3883

In [ ]:
movies1['Title'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
3892     True
3893     True
3894     True
3896     True
3897     True
Name: Title, Length: 3895, dtype: bool

In [ ]:
movies1.duplicated().sum()

np.int64(1)

In [ ]:
movies1[movies1.duplicated()]

MovieID                    Title          Genres
3887        3  Grumpier Old Men (1995)  Comedy|Romance

In [ ]:
movies1[movies1.duplicated(keep=False)]

MovieID                    Title          Genres
2           3  Grumpier Old Men (1995)  Comedy|Romance
3887        3  Grumpier Old Men (1995)  Comedy|Romance

In [ ]:
movies1.drop_duplicates(inplace=True)
movies1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3894 entries, 0 to 3897
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MovieID  3894 non-null   int64 
 1   Title    3894 non-null   object
 2   Genres   3894 non-null   object
dtypes: int64(1), object(2)
memory usage: 121.7+ KB


<ipython-input-56-9bddbd4607ba>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1.drop_duplicates(inplace=True)


In [ ]:
movies1[movies1['MovieID'].duplicated(keep=False)]

MovieID                               Title  \
5           6                         Heat (1995)   
6           7                      Sabrina (1995)   
7           8                 Tom and Huck (1995)   
8           9                 Sudden Death (1995)   
9          10                    GoldenEye (1995)   
11         12  Dracula: Dead and Loving It (1995)   
12         13                        Balto (1995)   
13         14                        Nixon (1995)   
14         15             Cutthroat Island (1995)   
16         17        Sense and Sensibility (1995)   
17         18                   Four Rooms (1995)   
3883        6                         Heat (1995)   
3885        8                      Sabrina (1995)   
3886        9                 Tom and Huck (1995)   
3888       10                 Sudden Death (1995)   
3890       12                    GoldenEye (1995)   
3891       13      American President, The (1995)   
3892       14  Dracula: Dead and Loving It (1995)   
3893        7                      Jumanji (1995)   
3894       15                        Balto (1995)   
3896       17                        Nixon (1995)   
3897       18             Cutthroat Island (1995)   

                            Genres  
5            Action|Crime|Thriller  
6                   Comedy|Romance  
7             Adventure|Children's  
8                           Action  
9        Action|Adventure|Thriller  
11                   Comedy|Horror  
12            Animation|Children's  
13                           Drama  
14        Action|Adventure|Romance  
16                   Drama|Romance  
17                        Thriller  
3883                Crime|Thriller  
3885                 missing genre  
3886          Adventure|Children's  
3888                        Action  
3890              Action|Adventure  
3891          Comedy|Drama|Romance  
3892                 Comedy|Horror  
3893  Adventure|Children's|Fantasy  
3894    Animation|Children's|Drama  
3896                         Drama  
3897                 missing genre

In [ ]:
movies1[['MovieID','Title']]=movies1[['MovieID','Title']].drop_duplicates(inplace=True)
movies1.info()



<class 'pandas.core.frame.DataFrame'>
Index: 3894 entries, 0 to 3897
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MovieID  0 non-null      object
 1   Title    0 non-null      object
 2   Genres   3894 non-null   object
dtypes: object(3)
memory usage: 121.7+ KB


<ipython-input-38-9bca120d5694>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1[['MovieID','Title']]=movies1[['MovieID','Title']].drop_duplicates(inplace=True)
<ipython-input-38-9bca120d5694>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1[['MovieID','Title']]=movies1[['MovieID','Title']].drop_duplicates(inplace=True)


In [ ]:
movies1.drop_duplicates(subset=['MovieID','Title'],inplace=True)
movies1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3893 entries, 0 to 3897
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   MovieID  3893 non-null   int64 
 1   Title    3893 non-null   object
 2   Genres   3893 non-null   object
dtypes: int64(1), object(2)
memory usage: 121.7+ KB


<ipython-input-58-81b097c343c0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1.drop_duplicates(subset=['MovieID','Title'],inplace=True)


In [ ]:
ratings=pd.read_csv('/content/ratings.csv')
ratings.head()

UserID  MovieID  Rating    Timestamp
0       1     1193     5.0  978300760.0
1       1      661     3.0  978302109.0
2       1      914     3.0  978301968.0
3       1     3408     4.0  978300275.0
4       1     2355     5.0  978824291.0

In [ ]:
ratings[['UserID','MovieID']].duplicated().sum()

np.int64(3)

In [ ]:
ratings=ratings.sort_values(by='Timestamp')
ratings.head()

UserID  MovieID  Rating    Timestamp
1000138    6040      858     4.0  956703932.0
1000153    6040     2384     4.0  956703954.0
999873     6040      593     5.0  956703954.0
1000007    6040     1961     4.0  956703977.0
1000192    6040     2019     5.0  956703977.0

In [ ]:
ratings.drop_duplicates(subset=['UserID','MovieID'],keep='last',inplace=True)
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000222 entries, 1000138 to 1000218
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   UserID     1000222 non-null  int64  
 1   MovieID    1000222 non-null  int64  
 2   Rating     1000221 non-null  float64
 3   Timestamp  1000220 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 38.2 MB


In [ ]:
ratings.groupby('MovieID')['Rating'].mean().reset_index()

MovieID    Rating
0           1  4.147257
1           2  3.200855
2           3  3.016701
3           4  2.736842
4           5  3.006757
...       ...       ...
3701     3948  3.635731
3702     3949  4.115132
3703     3950  3.666667
3704     3951  3.900000
3705     3952  3.780928

[3706 rows x 2 columns]

In [ ]:
ratings_agg= ratings.groupby('MovieID').agg({'Rating':'mean','Timestamp':'count'}).reset_index()

In [ ]:
ratings_agg.rename(columns={'Rating':'avg_rating','Timestamp':'rating_count'},inplace=True)

ratings_agg.head()

MovieID  avg_rating  rating_count
0        1    4.147257          2078
1        2    3.200855           702
2        3    3.016701           478
3        4    2.736842           171
4        5    3.006757           296

In [ ]:
pd.merge(movies1,ratings,on='MovieID',how='left')

MovieID                    Title                       Genres  \
0              1         Toy Story (1995)  Animation|Children's|Comedy   
1              1         Toy Story (1995)  Animation|Children's|Comedy   
2              1         Toy Story (1995)  Animation|Children's|Comedy   
3              1         Toy Story (1995)  Animation|Children's|Comedy   
4              1         Toy Story (1995)  Animation|Children's|Comedy   
...          ...                      ...                          ...   
1003467       18  Cutthroat Island (1995)                missing genre   
1003468       18  Cutthroat Island (1995)                missing genre   
1003469       18  Cutthroat Island (1995)                missing genre   
1003470       18  Cutthroat Island (1995)                missing genre   
1003471       18  Cutthroat Island (1995)                missing genre   

         UserID  Rating     Timestamp  
0        6035.0     4.0  9.567128e+08  
1        6032.0     4.0  9.567181e+08  
2        6022.0     5.0  9.567558e+08  
3        6021.0     3.0  9.567571e+08  
4        6016.0     4.0  9.567788e+08  
...         ...     ...           ...  
1003467   349.0     3.0  1.023243e+09  
1003468  3562.0     1.0  1.023984e+09  
1003469  1425.0     2.0  1.025198e+09  
1003470   752.0     4.0  1.029310e+09  
1003471  1019.0     2.0  1.035568e+09  

[1003472 rows x 6 columns]

In [ ]:
ratings.shape

(1000222, 4)

In [ ]:
movies1.shape

(3893, 3)